---
sudo: true
language: ruby
cache: bundler
before_install:
- sudo apt-get install libzmq3-dev
rvm:
- jruby-1.7.25
script:
- bundle exec rspec spec
- bundle exec rspec spec --tag integration
jdk: oraclejdk8
